### ISSUE TITLE
Vue 3 support

### ISSUE THREAD

**Issue by robert-cronin** [emedware/vue-golden-layout#120]
This might be a bit premature but Is there any plan to support Vue 3 in the near future?

**Comment by eddow** [comment]
Sorry for latency, I thought I answered here already.
It indeed has one blocker that could demand quite some work; so it's not really considered an emergency for now

**Comment by eddow** [comment]
So, it seems golden-layout v2 has a native vue-3 support.
[](https://github.com/golden-layout/golden-layout#vue)
I guess this topic has become obsolete.
