### ISSUE TITLE
"emitBubblingEvent" error on addition of tab

### ISSUE THREAD

**Issue by deadbeef404** [emedware/vue-golden-layout#121]
This affects the official demo page, and also happens when running the code in my own environment.

Steps to reproduce:
In the demo, simply click the "Add" button under the "CompA" heading, and this error will appear:

Result:
`[Vue warn]: Error in callback for watcher "state": "TypeError: Cannot read property 'emitBubblingEvent' of null"`

Source of error:
It comes from the golden child `innerStateChanged` function, because the `glObject` attribute seems to be undefined:

```
    goldenChild.prototype.innerStateChanged = function () {
        this.glObject.emitBubblingEvent('stateChanged');
    };
```

**Comment by eddow** [comment]
Done in 2.1.1
