### ISSUE TITLE
Expose the "shown" event

### ISSUE THREAD

**Issue by wenoptics** [emedware/vue-golden-layout#124]
Hi eddow, great work on this!

Looks like there's a "`shown`" event being added on upstream a while ago (https://github.com/golden-layout/golden-layout/pull/124), though not being documented yet (see https://github.com/golden-layout/golden-layout/issues/269).

Would be great if we could have it on vue-golden-layout

**Comment by eddow** [comment]
Done (with "showed") in 2.1.1
