### ISSUE TITLE
Drag sources

### ISSUE THREAD

**Issue by Taaitaaiger** [emedware/vue-golden-layout#133]
Hi,

One way to create new `contentItem`s in Golden Layout is to use `createDragSource` which
> Turns a DOM element into a dragSource, meaning that the user can drag the element directly onto the layout where it turns into a contentItem.

I can't find a reference to this method in `vue-golden-layout`'s codebase or the readme, I can access it by handling the `initialised`-event (the first child of the App-object has the `gl`-field). In order to get the TS to compile I need to add `// @ts-ignore` so I don't think this is the right approach. 

Is this supported, and if so, how do you recommend creating drag sources?

Thanks in advance!

**Comment by eddow** [comment]
Well, it is not "implemented" at all per-se.

However, using something like `<golden-layout ... ref="layout"`>`, `this.$ref.layout.glo` will access a promise who provide (when initialised) the "native" `GoldenLayout` object, who provides all these functions.

I should definitively add this to the doc.
