### ISSUE TITLE
How to Change Activate Tab

### ISSUE THREAD

**Issue by adeuran** [emedware/vue-golden-layout#35]
I want change Activate Tab.
like this (This code is for Golden-Layout Library.)
`item.parent.header.parent.setActiveContentItem(item);`

How can I access that method?

**Comment by eddow** [comment]
Sorry, I didn't see this issue before.

The `gl-stack` and `gl-dstack` `model` is the `tab-id` of the selected tab. This is why the components have the property `tab-id`.

```html
<gl-stack v-model="openedTab">
  <glComponent tab-id="comp1" ... />
  <glComponent tab-id="comp2" ... />
</gl-stack>
```

```ts
  onSomething() {
    this.openedTab = "comp2";
  }
```
