### ISSUE TITLE
Easiest sample

### ISSUE THREAD

**Issue by bromoapp** [emedware/vue-golden-layout#37]
Hi,

I just recently learn Vue and needed to implement your layout lib into it.
I studied the basic use of Golden Layout from their original site.
Is there any really simple (most basic) Vue project that you can show me on how to implement your lib into the newly created Vue app? Or at least point me to the right tutorial? where we are still using JS instead of TS?

Thanks
Bromo

**Comment by eddow** [comment]
Hello,

Unfortunately, I am the only one working on that project right now and I didn't find time to re-write a decent documentation - though README.md is already quite complete

For an example, you can clone the repository and it comes with a demo application - indeed, the one I use to test the functionalities as I develop them.
Here is the [installation guide](https://github.com/emedware/vue-golden-layout#installation)
