### ISSUE TITLE
Nested Components?

### ISSUE THREAD

**Issue by amadoalmex** [emedware/vue-golden-layout#38]
Is there a way to  achieve the following configuration?
![Selection_20190508-004](https://user-images.githubusercontent.com/31776001/57405454-173d9d80-71a4-11e9-8364-3d9ef1da177e.png)

I  tried: 
```
<gl-stack>
..
                        <gl-row title="this is barr">
                            <gl-component>
                                <h3>bar</h3>
                            </gl-component>
                            <gl-component>
                                <h3>barzzz</h3>
                            </gl-component>
                        </gl-row>
..
</gl-stack>
```

but I  get this:  (does not show gl-row title)]
![Selection_20190508-005](https://user-images.githubusercontent.com/31776001/57405890-2b35cf00-71a5-11e9-91a4-67ea95b099df.png)

**Comment by eddow** [comment]
I am indeed actively working  on that topic.
It unfortunately only happens in the branch feature/tab-container. What you describe here is already done but I am finishing the fact that a route can contain a layout part.
I am not sure if the branch has ever achieved a roughly stable version, but I hope to finish it this month

**Comment by eddow** [comment]
So, your example should be working with the version 1.6.0 I just published.
Feel free to re-open if you encounter any problem.
