### ISSUE TITLE
Container doesnt emit resize event

### ISSUE THREAD

**Issue by njbrown** [emedware/vue-golden-layout#39]
I bind a @resize event to a `gl-col` but it doesnt get called when I resize the container. The only event that seems to work is `@destroy`.
```
<gl-col width="55" @resize="resizeCanvas">
</gl-col>
```
Am I doing something wrong is the resize event just missing?

**Comment by njbrown** [comment]
I worked around this by catching container I want from the itemCreated event on the golden-layout element
```
<golden-layout class="hscreen" @itemCreated="itemCreated">
```

```
itemCreated(item: any) {
    if (item.config.title == "Editor") {
      item.container.on("resize", function() {
        console.log("resize!");
      });
    }
  }
```

**Comment by eddow** [comment]
Thanks for the report.
The event binding should happen [here](https://github.com/emedware/vue-golden-layout/blob/dce43f11c07b11a4823ba8932d6284d6faaa42f2/src/golden.vue#L336).

Now, I did test it at a time and didn't keep automatic testing :  the project is undergoing more important development for now.
Perhaps also `forwardEvt`is not called for containers, this part might have disapeared with time. Please let me know if you wish to PR on that, if not, I might try later to investigate - though with no calendar.

**Comment by eddow** [comment]
Hello,

Finally I could have an eye on it. Indeed, `golden-layout` does not even bother to throw such events. I henced explained it in the docs:

- Only the components'events matter as even elements from a container can be moved in another containers
- Containers are created and destroyed as the user move the components in the layout

And thinking about it, I wonder which use-case would lead someone to use `@resize` on a `gl-row` for example.

**Comment by eddow** [comment]
So, the fact is that `@resize  is only raised on components. I clarify the documentation as I clean the code that is responsible of that.
