### ISSUE TITLE
When a GL tab is closed, the Vue component is not destroyed

### ISSUE THREAD

**Issue by martincarles** [emedware/vue-golden-layout#41]
First, I'd like to thank you for your work on the repo. It's working great so far but we ran into a few issues and I'll describe one below.

I tried using your test sandbox but I would not compile so I created this small repo (with v1.5.12) to demonstrate one of my issues: https://github.com/martincarles/vgl-sandbox
This repo is as simple as I can make it: I have 5 components simply displaying the component name and accessible from a list of router-links at the top of the page.

**To reproduce my issue:**
- open all the links (About, Test 1, 2, 3 etc.): the GL tabs are correctly opened
- close some of the tabs
- open the Vue dev tools and inspect the virtual DOM

**Result:**
the components present in the closed GL tabs are still mounted on the virtual DOM

I would expect the Vue components to be destroyed from the Virtual DOM.
As a consequence, the number of vue components mounted on the virtual DOM only grows and I can't see any garbage collection happening. So as a result all the reactive properties from the non-destroyed components are still active and start to slow my app down until I actually refresh the page.

Is there anything wrong I'm doing here? It might be an obvious one hopefully or maybe it's expected behavior? 

Thank you for your help

**Comment by eddow** [comment]
Hello,

Sorry for late responsse. The bug will be solved in the next "release", it is part o a quite wider modification

**Comment by eddow** [comment]
PR merged with the resolution of this bug
