### ISSUE TITLE
Using vue-golden-layout with vue-electron template

### ISSUE THREAD

**Issue by abrown28** [emedware/vue-golden-layout#49]
I am getting an `Injection "layout" not found` error after the following steps.

```
vue init simulatedgreg/electron-vue test-gl
cd test-gl
yarn
yarn add vue-golden-layout
yarn add vue-property-decorator
```

I added the following lines to my src/renderer/main.js file.
```
import vgl from 'vue-golden-layout'
import 'golden-layout/src/css/goldenlayout-light-theme.css'

Vue.use(vgl)
```
I added the following to my src/renderer/App.vue template section
```
  <div id="app">
    <golden-layout>
      <gl-row>
        <gl-component title="component1">
          <h1>Component 1</h1>
        </gl-component>
        <gl-stack>
          <gl-component title="component2">
            <h1>Component 2</h1>
          </gl-component>
          <gl-component title="component3">
            <h1>Component 3</h1>
          </gl-component>
        </gl-stack>
      </gl-row>
    </golden-layout>
  </div>
```
I then ran `yarn run dev` to test.

I got an `Unexpected token .` error so I modified the .electron-vue/webpack.renderer.config.js to  add vue-golden-layout to the whiteListedModules array.

Now I'm getting the `Injection "layout" not found` error and I can't figure out where to go from here.

I also got the injection error for belongGroupColor.

Any help would be appreciated.

**Comment by eddow** [comment]
Hello,

The `Injection "layout" not found` error means that a golden component (component or row or ...)  is not in a golden-layout. Unfortunately, reproducing the simple exemple does not reproduce the error for me. Perhaps for an advise, try with only one component and rebuild the/an example little by little?

**Comment by eddow** [comment]
Also, I just thought about, the `Unexpected token .` error could be solved by importing directly the sources (if you use typescript)  by importing `vue-golden-layout/src` instead of white-listing.

Please re-open if a problem persist.

**Comment by shaohaojiecoder** [comment]
> Also, I just thought about, the `Unexpected token .` error could be solved by importing directly the sources (if you use typescript) by importing `vue-golden-layout/src` instead of white-listing.
> 
> Please re-open if a problem persist.

hi, Brother:
I meet this error too. but I does't use typescript, Could you give me some good idea, thanks
