### ISSUE TITLE
TypeError: "this.glObject.parent is null"

### ISSUE THREAD

**Issue by stephanepericat** [emedware/vue-golden-layout#51]
Vue Golden Layout Version: ^2.0.1
Nuxt.js version: ^2.0.0

I am trying to integrate Vue Golden Layout in a Nuxt.js application.
While it does render properly, I am running into an issue when leaving the current route (using vue-router) : 

```
TypeError: "this.glObject.parent is null"
    destroyed vue-golden-layout.js:3013
```

<img width="379" alt="Screen Shot 2019-11-06 at 10 28 42 AM" src="https://user-images.githubusercontent.com/161823/68318025-b70bb380-0081-11ea-9864-52ce463032cd.png">

By doing a bit of debugging, I traced it down to this line of code: 
https://github.com/emedware/vue-golden-layout/blob/master/src/roles/child.ts#L131

It seems like in some cases `this.glObject.parent` is null, so its existence needs to be checked in the conditional, something like : 

```javascript
this.glObject && this.glObject.parent && ~this.glObject.parent.contentItems.indexOf(this.glObject)
```

**Comment by stephanepericat** [comment]
it makes it so i cannot leave the route...

<img width="1792" alt="Screen Shot 2019-11-06 at 10 50 55 AM" src="https://user-images.githubusercontent.com/161823/68319096-5ed5b100-0083-11ea-8fee-3c09273072f9.png">

**Comment by eddow** [comment]
There are 2 cases when glObject is null: before it is initialised, or after it is destroyed. Do you have a clue of what could be the case here ?

**Comment by stephanepericat** [comment]
It happens when navigating away, so i wonder of maybe the parent is destroyed before destroying the gl instance ?

I tried to manually call `$destroy` on the gl instance using the `beforeRouteLeave` hook, but I get the same behavior.

I will put together a sample project to demonstrate the issue.

**Comment by eddow** [comment]
Thank you

**Comment by stephanepericat** [comment]
Here is a demo project showing the issue:

https://github.com/stephanepericat/gl-bug-demo

Please see the README for reproduce steps :)

**Comment by eddow** [comment]
I will include a fix for 2.0.2 and close the bug when I publish

**Comment by stephanepericat** [comment]
awesome, thank you :)

**Comment by stephanepericat** [comment]
hi @eddow , I updated to 2.0.2 and the issue is fixed :) thank you!
