### ISSUE TITLE
Applying a state that doesn't perfectly match the current container throws exceptions

### ISSUE THREAD

**Issue by jerkald** [emedware/vue-golden-layout#54]
If you persist the state of a golden-layout container, then modify your html to remove a gl-component, upon loading the previous state (which has data for the removed component), you get the following exception:

```
Uncaught TypeError: Cannot read property 'childMe' of undefined
    at VueComponent.goldenContainer.vueChild (container.ts:83)
    at VueComponent.goldenContainer.getChild (container.ts:52)
    at VueComponent.goldenContainer.getChild (container.ts:54)
    at VueComponent.goldenContainer.getChild (container.ts:54)
    at VueComponent.goldenLayout.getSubChild (golden.vue?./node_modules/ts-loader??ref--0!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/source-map-loader:144)
    at new eval (golden.vue?./node_modules/ts-loader??ref--0!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/source-map-loader:214)
    at new lm.items.Component (goldenlayout.js:3703)
    at lm.LayoutManager.createContentItem (goldenlayout.js:828)
    at lm.items.Stack._createContentItems (goldenlayout.js:3596)
    at lm.items.Stack.lm.items.AbstractContentItem (goldenlayout.js:3101)
```

Steps to reproduce.
1. Open the demo and move some tabs around.
2. Go to the demo code and comment out the gl-component block for 'compA' in demo-stack.vue
3. Reload the page, see the error.

I'm not sure if this is something that a developer should somehow handle but, maybe this library could also just ignore unknown components and include some additional safety checks.

**Comment by eddow** [comment]
Indeed, the state and the components should fit.
That is why the demo has down-right the screen the "Reset state" button
From README.md: "In order to reload a state, the Vue object structure must be reloaded identical too"

**Comment by jerkald** [comment]
The downside of this approach is that if the layout were to ever change then the exception will be thrown and the page will load incorrectly.

I understand that the demo has a big button to clear the local storage as a way to remove a bad state, but is that your only recommendation for anyone who uses this library? 

ie. Are our only choices, either to have a button to clear the state or we can never change our layout?

 Do you have any ideas for an approach that a developer could write so that we can catch this bad state so that the user doesn't have to know they need to click a button? 

 Since the state is only applied once and in mount, using the created and beforemount vue life cycle hooks might work, but there is no access to the template.  That makes it difficult to parse through and know if an element exists or not. My thought was to determine if we are trying to load something that has been removed and get it out of the state before it is applied at mount. But again, I don't see a way to get at that information before mount.

I also tried making a component to fit inside a golden-layout component that would wrap all the children col/row/component objects to see if I could check after those get mounted, but the library expects all top level children of a golden-layout component to have getChild methods among other gl related stuff.

Suggestions would be apprecated.

**Comment by eddow** [comment]
So, two things.

1- The exception is raised when you change the .vue source code. The user never changes the source code, when the layout is changed dynamically by the user, the exception does not raise.
If you change your program, then you should test from a fresh state - the exception occurs only if the structure has been changed programatically

2- for your late question (about a container of row/cols/...) check [here](https://github.com/emedware/vue-golden-layout#glcustomcontainers)

**Comment by jerkald** [comment]
Thank you for your time in answering my questions.

1 - Yes, I do understand this. 

The problem I'm trying to point out is that since the library does not take any precautions, the developer must write additional logic to handle this common situation.  Rarely will a layout stay the same for the duration of a website lifetime.

  The user won't understand what is going on nor will they know they need to clear their local storage. So it puts the burden on the developer to create a system so that this doesn't happen. Thus why I asked if additional safety checks could have been placed into the library to perhaps ignore unknown components. 

It sounds like your answer is that we should be clearing the state preemptively before loading. Losing the previously stored dynamic layout.  I was hoping for something more robust, but it is what it is.


2.  I will look into the glCustomContainers.    I'm not totally certain, but it sounds like it could be used for the purposes I'm trying to address.

Again, thank you.

**Comment by eddow** [comment]
> Rarely will the source of a layout stay the same for the duration of a website lifetime.

Indeed, this part is not at all taken into consideration. Unfortunately, this is not taken at all into considerations as it can lead to several use-case and different ways  of resolutions.

G-L states remembers each components. Adding a component in a layout-update could demand a manual re-writing of the saved state for it to be completely transparent, and it would demand the library to be aware of the changes of layout beside the layout itself. Another way would be to have a list of sub-components to add manually from drag-n-drop and add a new drag-n-drop source; or a "state refresh" that occurs not on button-click but on layout update (based on a version nr for ex). It really depends of your use-case here.

Though, the question is worth wondering; I don't think we can find an automatic way to solve this, but it's worth wondering if you have any idea, there are perhaps ways to find hybrid ideas who would "refresh" just the part of the layout who is problematic.
