### ISSUE TITLE
this.container.width is not a function

### ISSUE THREAD

**Issue by timster** [emedware/vue-golden-layout#55]
I created a new project and added vue-golden-layout.

Things seem to work generally fine, but I get the following error in the console:

```
TypeError: this.container.width is not a function
    updateSize  goldenlayout.js:727
    onResize    vue-golden-layout.js:1215
    <anonymous> self-hosted:876
    i           Vueresize.js:1
    call        ResizeSensor.js:128
    onResized   ResizeSensor.js:269
```

<img width="471" alt="Screen Shot 2020-02-13 at 3 49 49 PM" src="https://user-images.githubusercontent.com/173666/74477170-c9fc0400-4e78-11ea-962a-cdf9722d41f5.png">

Here is a sample repository that exhibits the issue:

https://github.com/timster/test-golden-layout

Looks like some kind of issue caused by `onResize` then eventually calling `updateSize` in golden layout which tries to do `this.container.width` but this.container is undefined on first render.

**Comment by timster** [comment]
To follow up... I edited goldenlayout.js to log the value of `this.container`. It seems as. though the first call is not a jquery object, but the others are:

<img width="478" alt="Screen Shot 2020-02-13 at 4 06 00 PM" src="https://user-images.githubusercontent.com/173666/74478193-d6815c00-4e7a-11ea-9294-650472e212ca.png">

**Comment by eddow** [comment]
Hello,
The error seems to indicate a `container` is not initialised.
I installed `test-golden-layout` but couldn't reproduce the bug - do I have to make a specific manipulation ?

**Comment by timster** [comment]
What browser did you use? Sometimes I don’t get it in Safari. But it always happens in Firefox.

**Comment by eddow** [comment]
I usually use Chrome. I just tried it here with firefox, with the same result : no reproduction

**Comment by timster** [comment]
That's strange. I can only duplicate it in Firefox.

I figured out that for some reason in some cases it's calling `onResize` before goldenlayout is initialised. I'm not sure if it's a caching issue or a timing issue or whatever.

I changed the `onResize` function to this (added check for this.gl.isInitialised)

```js
onResize() { this.gl && this.gl.isInitialised && this.gl.updateSize(); }
```

Would you be open to a PR for this addition? It seems to fix the issue with no adverse effects.

**Comment by jerkald** [comment]
I wanted to mention that I've also been seeing this error from time to time.  It isn't always reproducible and seems like it is almost random or based on timing.  I refreshed my page twice with no errors and then on the third time it did spit this out, with no changes to the underlying code.

Using chrome also.

![widtherror](https://user-images.githubusercontent.com/50713109/74668265-7cc6ad80-516a-11ea-82a3-04f7c55ce316.png)

**Comment by timster** [comment]
It's definitely because GL is not initialized yet. Fairly sure it's some kind of asynchronous timing thing since this library does `async mounted` so it's possible for `onResize` to get triggered before `this.gl.init()` is called in `mounted`

**Comment by eddow** [comment]
For my research by reverse-engeneering here, the case only occurs when `updateSize` is called without arguments and it seems to occur only in golden-layout `init`. 

In this function, the `updateSize()` call is preceded by a `_setContainer()` who should make sure the container is set to a valid dom-element.

As I can really not reproduce it here, may I please ask one of you to :

- set a conditional breakpoint on goldenlayout.js:727 with the condition `!this.container.width`
- describe here what kind of object `this.container` is

**Comment by timster** [comment]
In Safari, it's a jquery object every time:

<img width="296" alt="Screen Shot 2020-02-18 at 9 37 52 AM" src="https://user-images.githubusercontent.com/173666/74745832-7996f480-5232-11ea-8078-46936b097877.png">

However in Firefox, it's not a jQuery object the first time it's called (which is the cause of the error):

<img width="488" alt="Screen Shot 2020-02-18 at 9 38 33 AM" src="https://user-images.githubusercontent.com/173666/74745863-84ea2000-5232-11ea-829f-436c8023d6f4.png">

**Comment by timster** [comment]
A little more troubleshooting. I added a `console.log` to the `onResize` function in vue-golden-layout. Here are the logs for a fresh page reload (no window resized).

In Safari, onResize is not called right away, and when it's first called, goldenlayout is initialized:

<img width="327" alt="Screen Shot 2020-02-18 at 11 20 15 AM" src="https://user-images.githubusercontent.com/173666/74755682-7fe09d00-5241-11ea-8b9d-1bb0fde3c47e.png">

Chrome seems to be the same:

<img width="338" alt="Screen Shot 2020-02-18 at 11 27 48 AM" src="https://user-images.githubusercontent.com/173666/74755835-ba4a3a00-5241-11ea-94da-4f19f7d77b79.png">

However in Firefox, `onResize` is called first (before GL is initialized) which causes the problem:

<img width="405" alt="Screen Shot 2020-02-18 at 11 27 11 AM" src="https://user-images.githubusercontent.com/173666/74755768-9edf2f00-5241-11ea-84cf-02fa8af0e15f.png">

Seems very strange there is a difference in browsers.

**Comment by eddow** [comment]
I published a patched version where the jQuery element is given instead of the HTMLElement - please try 2.0.3 and close the bug accordingly

**Comment by timster** [comment]
Looks like that fixes the issue for us. Thanks for your help!
