### ISSUE TITLE
how to extend headers?

### ISSUE THREAD

**Issue by ioanwurf** [emedware/vue-golden-layout#56]
Hello! Your library looks like a great fit for an app I'm working on. 
I'm just wondering how to inject a Vue component in the stack's header, similar to this example: http://golden-layout.com/examples/#e15391fb136593e265013408cf68e561

Do you have any idea ? Thanks !

**Comment by eddow** [comment]
Like in the exemple.
```html
<gl-stack>
  ...
  <gl-component title="my component">
    <my-component />
  </gl-component>
  ...
</gl-stack>
```

**Comment by ioanwurf** [comment]
Thanks for your response @eddow, but I'm afraid you misunderstood my request. I see how to inject a vue-component into a gl-component, but I don't know how to inject a vue-component into the stack's header, just like the dropdown color menu in the linked example. Could you please give me a hint about that? Thanks a lot!

**Comment by eddow** [comment]
Oh, I see - sorry for the confusion.
There is unfortunately nothing planned in the library for that at the moment. It is neither really planned in the coming developments, so please try to go directly with golden-layout and keep me informed if you see an easy way to describe use-cases or implementations.

**Comment by 2xAA** [comment]
@eddow This is something I'm looking to use also. Extending tabs would be another feature of Golden Layout I'd like to use.

You can extend tabs fairly easily in the `mounted` hook of a `<GLComponent />` child Vue component using:

```JavaScript
this.$parent.$on("tab", tab => {
  // element is a jQuery reference, hence we can pass a string to append
  tab.element.append("<div>hello</div>");
});
```

I've been unable to extend headers yet as "elegantly" as you need a ref to the top-level `<GoldenLayout />` component to listen to `stackCreated` events.  
It may even be impossible to extend headers if you're attempting to extend from `<GLComponent />` children as their parent `glObject`s aren't available at the time of component mounting for some reason.

To me all of this feels extremely un-Vue-like and I'd prefer to use another API to do this if possible.

Do you think using Vue's [named slots](https://vuejs.org/v2/guide/components-slots.html#Named-Slots) in `<GlComponent />` would be a route to explore here?

I'd be willing to invest time to look into implementing this. Though I have to admit, TypeScript and writing Vue components with Class decorators are bit of a barrier to entry for me.
