### ISSUE TITLE
gl-router enters infinite loop when a pane is opened and there is no room in the d-stack header for the new tab

### ISSUE THREAD

**Issue by CS-Labs** [emedware/vue-golden-layout#57]
Hey, firstly I wanted to say thanks for the awesome library it's very useful.

I think we might have discovered a bug however. If I open a route/component that isn't already on the d-stack and there is no room left on the header of the d-stack to display the tab of the new component the router enters an infinite loops cycling between routes.

I'm able to reproduce this using the demo you provided (the only change I made was increasing the length of the table titles to replicate the overflow).

Attached is a .gif of what happens.
![bug](https://user-images.githubusercontent.com/11419702/75308606-24e41280-580c-11ea-9b51-3e88bfbbaf3c.gif)

Let me know if you need me to provide any more information.

Thanks!

**Comment by eddow** [comment]
Thanks for reporting.

Fixed in 2.0.4

**Comment by CS-Labs** [comment]
Awesome, thanks!
