### ISSUE TITLE
Programmatically Modify Rows/Cols/Stacks

### ISSUE THREAD

**Issue by BeeFishy** [emedware/vue-golden-layout#58]
Thanks for the great library, it's proving extremely useful on our project.

How would I go about accomplishing the Programmatic Reorder described for Golden Layout here: https://golden-layout.com/examples/#01249881a541bafcdf827c8b9020ad8a using the vue-golden-layout abstraction (i.e. given a column of components, allow the user to make an input (press button), and re-order the layout into a grid of rows and columns)?

As a follow-on, is there a way to programmatically add a column/row as a component is added?  For example, in the demo, when a user selects "test-c" how could the "C-test" component be brought up in a separate column or row, rather than in the A-test stack.

**Comment by eddow** [comment]
Well, the vue-router has been programmed as a d-stack, so changing the url just opens it in the same stack as the other routes.
To programatically add/remove components however, you can use Vue mechanisms with `v-for` and `v-if` like for the demo's `title="Bottom"` and `stackSubs` components

**Comment by eddow** [comment]
I forgot to answer about the re-arranging part - as you see in the exemple, the layout is destroyed and re-created. I am pretty sure this can be done with Vue mechanisms too, even though destroying the whole layout object and re-loading it with a different config could definitely do the job.
