### ISSUE TITLE
Golden layout doesn't resize on window resize

### ISSUE THREAD

**Issue by nmearl** [emedware/vue-golden-layout#60]
Golden layout remains at the size of the window on page load and doesn't seem to respond to window resizes.

**Comment by eddow** [comment]
Unfortunately, the size of the golden-layout object is not controlled by the golden-layout itself, but by the size of its container.
This is why in the example we use the CSS `sw` and `sh` (resp. "screen-width" and "screen-height") to make it follow the client area size.
Try without the golden-layout, just to have an empty div with a flashy (red?) background to see it following the sizing use-cases you have, then just set the golden-layout into that div
