### ISSUE TITLE
Conditionally render glRow

### ISSUE THREAD

**Issue by VasilisNikiforidis** [emedware/vue-golden-layout#64]
This is more of a **question** than an issue, but others may face similar issues so here it is:

I have a layout which contains 2 columns, the 2nd column contains 2 rows.
Of these 2 rows I want the second one to be rendered based on certain conditions,
so I have a `v-if="bottomRowVisible"` on the 2nd row where `bottomRowVisible` is a computed variable,
which returns true or false based on some conditions.
I have a watcher on the variable, so I know that the conditions work fine and the variable changes correctly. 
Initially the variable returns false.

My problem is that when the variable becomes true for the 1st time, the glRow renders normally, but if I close it (conditions updating as they should and `bottomRowVisible` becomes false), and then trigger something which changes the conditions and `bottomRowVisible` becomes true again, the glRow is never rerendered.

Any suggestions are welcome :)

P.S.: If I have not been clear enough, I would be happy to give more details.
P.S.2.: The same code worked in v1

**Comment by eddow** [comment]
Well, it's a bit hard to answer like that as you describe the exact example from the demo application.
If really you see no difference between the demo application and yours, could you please make a sample repository?

**Comment by VasilisNikiforidis** [comment]
To my understanding, in the demo, the stack and its parent are already rendered and never closed thus items can be rendered at any time inside them.
My problem is that I want to dynamically render a container, namely glRow and not just a glComponent

**Comment by eddow** [comment]
If you click on the "Toggle" button in the demo (in "compA"), you will see your use case in action

**Comment by VasilisNikiforidis** [comment]
Damn I'm blind...

I saw the example you are talking about, but the v-if is still on a "gl-component" item.
Would it have the same effect in any gl object, e.g. gl-col, gl-row etc?
If yes, something else I am doing must be wrong, if no perhaps I should change my gl object to a "gl-component"?

**Comment by eddow** [comment]
Well, when you close the component manually, the component is closed - and indeed the row is closed automatically.
Now, it you try to show again the row, it will perhaps show - but if it does, it will be empty as the component is closed.
I think it will just now show though as it is empty.

**Comment by eddow** [comment]
Please re-open if you still find a problem on the topic

**Comment by VasilisNikiforidis** [comment]
Reopening since I found out the real reason (I think).

Apparently, by using chrome debugger, I found out that when the `addChild` method in goldenLayout.js is called due to the v-if being true, the second time, the column which the conditional row should be added has no content items, which is wrong, because this column has one row which is always rendered. 

So my guess is that it either inserts the conditional row in a clone of the correct column or there is some issue with the reactivity? The same is true even when I use a simple gl-component instead of row-stack-component.

My layout in that area is like this:
`
<golden-layout>
    <gl-row>
        <gl-col>
        ...
        </gl-col>
        <gl-col>
            <gl-row>
            ...
            </gl-row>
            <gl-row v-if="enabler">
            ....
            </gl-row>
        </gl-col>
    </gl-row>
</golden-layout>
`

Each of these row/columns have widths and heights assigned to them if this plays any role.

**Comment by eddow** [comment]
Please leave here the complete code corresponding to:
````xml
            <gl-row v-if="enabler">
            ....
            </gl-row>

**Comment by VasilisNikiforidis** [comment]
```
<gl-row :height="1" ref="bottomRow" v-if="enabler" title="bottomRow">
    <gl-stack :width="10" ref="stackBottom">
        <gl-component
            v-if="!_.isEmpty(compilationErrors)"
            @destroy="clearCompilationResults"
            title="Output" 
            tabId="Output"
        >
            <div v-for="(msg,name) in compilationErrors" :key="name" class="compileResults">
                <span class="compiledName">
                    {{name}}:
                </span> 
                <span class="compiledMsg">
                    {{msg}} 
               </span>
            </div>
        </gl-component>
        <gl-component
            v-if="debugSession"
            title="Debugger" 
            @destroy="debug"
             tabId="Debugger"
        >
            <Debugger/>
        </gl-component>
    </gl-stack>
</gl-row>
```

Tell me if anything needs to be clarified.
For now the enabler is just a boolean variable in data which changed by a button click I put just for testing purposes.

**Comment by eddow** [comment]
I'm trying this in the demo application and it does not reproduce:
```xml
				<gl-row v-if="demoStackState.bottomSheet">
					<gl-stack>
						<gl-component title="Bottom" @destroy="demoStackState.bottomSheet = false">
							<p>Routes: {{routes}}</p>
						</gl-component>
					</gl-stack>
				</gl-row>
```
Are you sure that `enabler` is only modified by a button outside and that you never close the component "manually" (by clicking on the cross) in your tests ?

**Comment by VasilisNikiforidis** [comment]
Yeah cause I tried to replicate the demo in my code to help me figure out what's wrong. The button just does this: 
```
toggle() {
			this.enabler = !this.enabler
			console.log(this.$refs.layout)
		}
```
Would it matter if I closed it from the 'close' button?
I would just have to click the button one additional time to set the variable to false since I didn't change it at a @destroy event.

This is the error I get when hitting the button to set the enabler to false, after it wrongly put the element in the previous step. (cycle: false -> btn click -> true, element appears -> btn click -> false, element disappears -> btn click -> true, element does NOT appear -> btn click -> false, gets error)

![Capture](https://user-images.githubusercontent.com/42541460/77059846-49cd3f00-69e0-11ea-8c0f-234a256825f6.PNG)

**Comment by eddow** [comment]
Well, as I said, if you close the component with the "close" button, your whole code would be equivalent to :
```xml<gl-row :height="1" ref="bottomRow" v-if="enabler" title="bottomRow">
    <gl-stack :width="10" ref="stackBottom">
    </gl-stack>
</gl-row>
```
as the close button destroyed the component, so setting `enabler` to `true` again would display this empty structure.

Also, even if it seems related - what is that `<debugger />` tag?
- I'm quite interested for my own knowledge
- Try perhaps without that tag, just to be sure : we have another bug still opened related to vue-dev-tools

**Comment by VasilisNikiforidis** [comment]
Yeah I see how that would be confusing.
The debugger tag is a custom Vue component I created, pay it no mind, it has nothing to do with Vue dev tools or the browser debugger.

**Comment by VasilisNikiforidis** [comment]
I have even tried having only the 1st gl-component instead of the whole row.
Still the same :/

**Comment by VasilisNikiforidis** [comment]
Also I tried this in the demo and Toggle did not work. The first gl-stack did not play any role, tried it without it as well:

```
<gl-col>
					<gl-stack>
						<gl-row title="Bottom" v-if="demoStackState.bottomSheet" @destroy="demoStackState.bottomSheet = false">
							<gl-stack>
								<gl-component>
									<p>Routes: {{routes}}</p>
								</gl-component>
							</gl-stack>
						</gl-row>
					</gl-stack>
				</gl-col>
```

**Comment by VasilisNikiforidis** [comment]
Damn I think I found out the reason thanks to the above example in the demo.

The button I had was in a sibling of my conditional row's parent. Explaining:

```
<gl-col>
    <gl-row>
        <button/>
    </gl-row>
</gl-col>
<gl-col>
    <gl-row>
        ...
    </gl-row>
    <gl-row v-if="enabler">
        ...
    </gl-row>
</gl-col>
```

I then added a copy of that button in the 2nd gl-col inside a gl-component just between the 2 rows and it worked as expected while the above button still failed.
I guess it's got something to do with the trigger origin?
If you can confirm I would be happy to know, and sorry in advance for going on and on about it

**Comment by eddow** [comment]
No no, it's always a good idea to look out for bugs or might be bugs.
What you tell me still quite surprises me - can you confirm that rebundling+retrying with the old configuration still makes the bug ?

**Comment by VasilisNikiforidis** [comment]
```
<gl-col :width="10" :height="12" tabId="rightCol" ref="rightCol" title="rightCol">
				<gl-row ref="topRow" tabId="topRow" title="topRow">
					<gl-stack :width="10" ref="stackMain" tabId="stackMain">

						<gl-component
							title="Dashboard"
							:closable="false"
							tabId="Dashboard"
						>
							<unitDashboard/>
						</gl-component>

						<div v-if="openTabs[activeUnit]">
							<gl-component
								v-if="openTabs[activeUnit]['Code']"
								:title="tabTitle('Code')"
								@destroy="closeTab('Code')"
								tabId="Code"
							>
								<CodeComponents />
							</gl-component>

							<gl-component
								v-if="openTabs[activeUnit]['Data']"
								:title="tabTitle('Data')"
								@destroy="closeTab('Data')"
								tabId="Data"
							>
								<DataComponents />
							</gl-component>

							<gl-component
								v-if="openTabs[activeUnit]['Page']"
								:title="tabTitle('Page')"
								@destroy="closeTab('Page')"
								tabId="Page"
							>
								<PageComponents />
							</gl-component>

							<gl-component
								v-for="(props, name) in openTabs[activeUnit]['Resource']"
								:key="name"
								:title="tabTitle(name, props.type)"
								@destroy="closeTab('Resource', name)"
								:tabId="name"
							>
								<ResourceComponent :properties="props" :name="name"/>
							</gl-component>
						</div>
						
					</gl-stack>
				</gl-row>
				<gl-component style="display: none">
					<q-btn
						color="primary"
						label="click me"
						@click="toggle"
					/>
				</gl-component>
				<gl-row :height="1" ref="bottomRow" v-if="bottomRowVisible" tabId="bottomRow" title="bottomRow">
					<gl-stack :width="10" ref="stackBottom" tabId="stackBottom">
						<gl-component
							@destroy="clearCompilationResults"
							title="Output" 
							tabId="Output"
						>
							<div v-for="(msg,name) in compilationErrors" :key="name" class="compileResults">
								<span class="compiledName">{{name}}:</span> <span class="compiledMsg">{{msg}}</span>
							</div>
						</gl-component>
						<gl-component
							v-if="debugSession"
							title="Debugger" 
							@destroy="debug"
							tabId="Debugger"
						>
							<Debugger/>
						</gl-component>
					</gl-stack>
				</gl-row>
			</gl-col>
```

this is a wider view of my layout.
Apparently, when the component with the button simply exists there, even if i never click it, and the "bottomRowVisible" computed var changes between true and false, everything works fine.
If i comment out the gl-component with the `q-btn` element I does not work.
I am getting more confused the more I search for it :p

**Comment by VasilisNikiforidis** [comment]
I think I got somewhere :p

When I have a `gl-col` with only 1 static row and 1 dynamic, when the condition to show the dynamic row becomes false and the row is destroyed, the layout 'sees' a `gl-col` with only 1 `gl-row` and runs the `replaceChild` method, which removes the wrapper col and in its place puts the static row, so when the condition to show the dynamic row becomes true again, there is no `gl-col` item for it to be placed, thus failing to apper.
When I also had the `gl-component` with the button in the `gl-col` the layout did not replace the element because it had 2 children.

Please confirm my theory if possible, so I don't go mad :p

**Comment by NeverBehave** [comment]
> I think I got somewhere :p
> 
> When I have a `gl-col` with only 1 static row and 1 dynamic, when the condition to show the dynamic row becomes false and the row is destroyed, the layout 'sees' a `gl-col` with only 1 `gl-row` and runs the `replaceChild` method, which removes the wrapper col and in its place puts the static row, so when the condition to show the dynamic row becomes true again, there is no `gl-col` item for it to be placed, thus failing to apper.
> When I also had the `gl-component` with the button in the `gl-col` the layout did not replace the element because it had 2 children.
> 
> Please confirm my theory if possible, so I don't go mad :p

I think you are right, when adding >2 element in the layout does solve this problem.
