### ISSUE TITLE
Events not working

### ISSUE THREAD

**Issue by nmearl** [emedware/vue-golden-layout#65]
I'm finding that only a very few events actually seem to work for me (mainly the `resize` event on components). Things like the following aren't firing:

```vue
<golden-layout
  @stateChanged="consle.log($event)"
  style="height: calc(100% - 64px)"
  @selection-changed="consle.log($event)"
  :has-headers="settings.show_tab_headers"
  :selection-enabled="true"
>
  <gl-row @stateChanged="consle.log($event)" @selection-changed="consle.log($event)" :closable="false">
    <gl-stack
      v-for="(stack, index) in stack_items"
      :key="index"
      @selection-changed="consle.log($event)"
      :show-maximise-icon="false"
    >
      <gl-component
        v-for="(viewer, index) in stack.viewers"
        :key="index"
        title="Test"
        @resize="relayout"
      >
      ...
```

I've attempted using `@state-changed` or `@selectionChanged`, but I'm still not seeing anything in the console. What might I be doing wrong?

**Comment by eddow** [comment]
For the golden-layout object,

> The `golden-layout` has a *property* and an *event* named `state`.

So, the event to use on the `golden-layout` object is `state`.
The `selection-changed` event makes sense *only* on the `golden-layout` object. 
- It has no meaning on a `gl-row` object
- The `gl-stack` uses a completely different system to determine programatically the selected tab described here :

> - `tabId: string`: Used as the `v-model` of a `gl-stack` or `gl-dstack` to determine/set the active tab

This meaning that the components *in the `gl-stack`* must have a `tab-id` property.

Questions:
Is the `selection-changed` event called on the golden-layout object?
Is the `state-changed` event called on the `gl-row`object?

**Comment by nmearl** [comment]
> PS: It is highly unadvised to manage the state on a component (row, col, ...) level but manage the whole state of the golden-layout object directly

Good point. I was peppering the events around to try and see if I misunderstand to which component they were supposed to be attached.

> Is the selection-changed event called on the golden-layout object?

I've removed all other events and just ensured that the golden-layout object has `@selection-changed="console.log($event)"`, and I'm still not seeing anything in the browser console when I make selections.

> Is the state-changed event called on the gl-row object?

Removing all other events and just having `@state-changed="console.log($event)"` on the `gl-row` object, I'm not seeing anything in the browser console when I move tabs around.

**Comment by eddow** [comment]
Sorry for late response.

The `state-changed` event indeed should not be called on the `gl-row` object.

Beside, as indicated [here](http://golden-layout.com/docs/GoldenLayout.html) at the `selectionChanged` event - do you have the property `selectionEnabled` set to true?
