### ISSUE TITLE
Incorrect resize when dynamic component is toggled

### ISSUE THREAD

**Issue by VasilisNikiforidis** [emedware/vue-golden-layout#66]
Trying to find a workaround for #64 by changing my layout, I stumbled upon this.
When I have 3 columns and the 3rd one is dynamic (is toggled on and off), is I have a set width on the first column, it not only fails to resize to that width, but grows every time the dynamic row is toggled on and off. I reproduced this behavior in the demo as well with the following code in `app.vue`:

```
<div>
		<button class="reset" @click="reset">Reset localStorage</button>
		<golden-layout class="hscreen" v-model="state">
			<gl-row :closable="false">
				<gl-col width="30">
					<gl-stack>
						<gl-component>
							test
						</gl-component>
					</gl-stack>
				</gl-col>
				<gl-col>
					<gl-router empty-route="/a" :routes="routes">
						<template slot="route" slot-scope="{ meta }">
							<p-head :title="meta.title" />
							<main />
						</template>
					</gl-router>
					<demo-stack :state="demoStackState" />
				</gl-col>
				<gl-col title="Bottom" v-if="demoStackState.bottomSheet" @destroy="demoStackState.bottomSheet = false">
					<gl-stack>
						<gl-component>
							<p>Routes: {{routes}}</p>
						</gl-component>
					</gl-stack>
				</gl-col>
			</gl-row>
		</golden-layout>
	</div>
```

If the 1st column has no width set it resizes correctly, but that is restrictive to the layout

**Comment by eddow** [comment]
I cannot reproduce. (We don't see the cursor but I only repetitively click on "Toggle")
![toggle](https://user-images.githubusercontent.com/765511/78990766-fa41e500-7b3f-11ea-80d8-90bc60073a72.gif)

Note: I c/p-d your example

**Comment by VasilisNikiforidis** [comment]
I think you need to first click on the "Reset localstorage" otherwise it ignores the set width. As you can see your gif starts with the 1st column taking up half the screen where the width equals 30 so it should be about 1/3. Correct me if I am wrong

**Comment by NeverBehave** [comment]
The width at first loaded does work but fails after toggles. Does it related to the state/config reload?

**Comment by NeverBehave** [comment]
https://github.com/golden-layout/golden-layout/blob/f4a8ea9f2b6b4a9f65c61c36718a74e0c6901c28/src/js_es6/items/RowOrColumn.js#L76

It looks like if you dynamic added row/col, width will be re-calculated

**Comment by NeverBehave** [comment]
Here is a dirty fix, I have no clue how to make it better without changing goldenLayout. Basically override the calculation and do the math yourself.

Replace this if statement https://github.com/emedware/vue-golden-layout/blob/e2294ee26ebbd82804ef19fc240806bf1a33354a/src/roles/container.ts#L55

```js
        if (ci) {
          ci.addChild(child, undefined, true);
          const newItemSize = child[ci._dimension]
          for (let i = 0; i < ci.contentItems.length - 1; i++) {
                let itemSize = ci.contentItems[i].config[ci._dimension] *= (100 - newItemSize) / 100;
                ci.contentItems[i].config[ci._dimension] = itemSize;
        }
        ci.callDownwards('setSize');
        ci.emitBubblingEvent('stateChanged');
  } else { ... keep the rest the same
```

**Comment by NeverBehave** [comment]
@eddow do you think this one should be merged?

**Comment by eddow** [comment]
I unfortunately blindly c/p your solution but the demo begun to raise exceptions.
I let you dig about it, if you find a working solution to this problem, please don't hesitate to make a PR
