### ISSUE TITLE
Glitch when resizing inside a flexbox

### ISSUE THREAD

**Issue by grbd** [emedware/vue-golden-layout#67]
Hi,
I've been recently trying to use vue-golden-layout inside a flexbox via Quasar.
I've noticed a bit of a glitch when resizing, in that the golden-layout element will expand the height / width
but not shrink on resizing.

One way around this is to set the size to something like 100vw or a bit less in the styling like you've done in the demo.

``` css
.hscreen {
	width: 100vw;
	height: 100vh;
}
```

However it's not exactly perfect in terms of margins etc.
After a bit of digging I found that the issues is actually within golden-layout and not vue-golden-layout
The resize callback is being called properly on shrink within golden.vue
The problem appears to be somewhere within this.gl.updateSize()
In that goldent-layout isn't correctly determining the size of the container when shrinking, so only grows in size.

Sometimes it will work with the height but not the width and other times the width but not the hight
depending on the layout.

It looks like there hasn't been any releases for golden-layout for a while, but there has been a fair few commits
so it's possible it's fixed in the latest master code, but I wouldn't expect any new releases soon.
(I think it's being updated from es5 to es6 at the moment)

As a simple workaround which is a little hacky but works, is to just call the following on any resize
```
this.gl.updateSize(10,10)
this.gl.updateSize()
```

The first call shrinks the element to a minimum size, the second call then expands it to the container size
Even though it's a golden-layout issue I figured I'd mention it here since it took me a while to figure out

Option one would be to change
```
onResize() { this.gl && this.gl.updateSize(); }
```
To
```
onResize() { this.gl && this.gl.updateSize(10, 10); this.gl && this.gl.updateSize(); }
```

Option two to do something similar without changes to vue-golden-layout as an example

example1.vue
``` xml
<template>

  <q-layout view="hHh lpR fFf">

    <q-page-container>
      <q-page v-resize="onResize">

          <golden-layout ref="rootlayout"
                         class="q-pa-md"
                         style="min-height: inherit;"
                         :showPopoutIcon="false"
                         :showMaximiseIcon="false"
                         :showCloseIcon="false">
            <gl-row>
              <gl-stack>
                <gl-component title="component1">
                  Test1234
                </gl-component>
                <gl-component title="component2">
                  <h1>Component 2</h1>
                  test5678
                </gl-component>
              </gl-stack>
            </gl-row>
          </golden-layout>

      </q-page>
    </q-page-container>

  </q-layout>

</template>
<script src="./example1.ts"></script>
```

example1.ts
``` ts
import { Component, Vue, Prop } from 'vue-property-decorator';
import resize from 'vue-resize-directive';

@Component({
    components: {},
    directives: { resize }
})
export default class Example1Component extends Vue {

    $refs!: {
        rootlayout: any;
    }

    public onResize() {
        // This is to fix a bug associated with golden-layout's resize
        // We resize smaller first then let it auto grow afterwards
        this.$refs.rootlayout.gl.updateSize(10, 10);
        this.$refs.rootlayout.gl.updateSize();
    }
}
```

**Comment by eddow** [comment]
Thanks for reporting.
I tried and it doesn't seem to break anything beside.
It is in the git repo now, tell me if you need it published or if I wait further modification to publish again.

**Comment by grbd** [comment]
Thanks for adding this in
the only other change I added into my wrapper component was the use of 
```
v-resize:debounce.50="onResize"
```
instead of
```
v-resize:"onResize"
```

I noticed when the window was maximised then restored (to an unmaximised state) it would not trigger a onResize event otherwise
I'm not sure if that's something you want to add in as well
