### ISSUE TITLE
Unable to customize component size

### ISSUE THREAD

**Issue by Frankjunita** [emedware/vue-golden-layout#69]
When I tried to customize the widths above gl-component or gl-col, I got a messy view, where everything was compact on the far left of the view, unable to expand, like there was nothing in the view
`<gl-col width='80'>
          <gl-row>
            <gl-stack>
              <gl-component title="binance" :reorder-enabled="false" :closable='false'>
                {{msg}}
              </gl-component>
              <gl-component title="currency" :reorder-enabled="false">
                {{msg}}
              </gl-component>
            </gl-stack>
          </gl-row>
          <gl-row>
          </gl-row>
</gl-col>`

**Comment by eddow** [comment]
I cannot reproduce.
I c/p-d the code you gave directly in a golden-layout and this is my screen :
![image](https://user-images.githubusercontent.com/765511/80376396-6b083180-88a2-11ea-88ed-5a63e672cd5a.png)
