### ISSUE TITLE
add new hash key to config.content

### ISSUE THREAD

**Issue by SangJuBaek** [emedware/vue-golden-layout#73]
Hello!
Thank you for letting us to use great layout components!

Can I add an customized identifier for a user's needs in the config when creating an item?

(like when vue: '0' value added within config.content)

If it is impossible now, could you tell me if you have any plans for this feature?

**Comment by eddow** [comment]
Well, if you look at the demo application, adding a custom golden-layout-config item is not the preferred way to go. 
If a control should retain a value for it to be persisted, it should be persisted manually, beside the layout config.

Please, tell me if you have a use-case that does not fit the description or if it answered your question.

**Comment by SangJuBaek** [comment]
Oh..I think i need to find another way. Thank you!


I have another question.

I tried to use gl-col, gl-row, gl-stack through vue dynamic component , but it failed.

[Here is an example address.](https://github.com/SangJuBaek/gltest)

Could you tell me which part is wrong?

**Comment by tristanp2** [comment]
I'm also having issues from not being able to have some identifier for each gl-component. However, it's also possible that I'm taking the wrong approach for what I'm trying to accomplish.

Basically, each gl-component renders some instance of a Vue component. A user can instantiate multiple instances of the same component. My issue is in trying to save and reload the state. When I save the layout state, I also want to save some properties of the underlying Vue components. When I reload the state, these saved properties should be used to initialize the Vue components. Right now, I'm trying a hack which uses the componentName property of a gl-component's glObject to hold the identifier for the underlying Vue component. I look up the loaded component data by key and initialize the correct template with the correct values. 

Is there a better way to do this? I thought this method would be ok, but honestly it's turning into a bit of a mess.

**Comment by tristanp2** [comment]
@SangJuBaek 

I've found a decent way to do what I wanted to do, but I had to ditch this library and just use vanilla golden layout. It seems that maybe this library is written with more static apps in mind? Either way, I spent way too long trying to get this library to work for my purposes, and realized most of what I was doing was accessing the underlying golden layout functionality.

This is basically what I ended up doing: [https://github.com/arun-prakash-fokus/vue-goldenlayout-dynamic/blob/master/src/App.vue](url)

Using this method allows for much more control of how the state is stored and loaded, and it easily allows for dynamic container contents. Note that if you are using things like Vuex, you will probably want to define the parent when instantiating the dynamic components.

**Comment by eddow** [comment]
Hi guys, sorry to be late.
So, to try to answer, I would point you to the demo application [here](https://github.com/emedware/vue-golden-layout/blob/master/demo/app.vue)
```typescript
	@Persist() state: any = null
	@Persist() demoStackState = {
		bottomSheet: false,
		stackSubs: [1],
		ssId: 1
	}
```
As you can see, the `vue-state` (here `demoStackState`) is persisted in **parallel** of the `gl-state` (here `state`).

Don't forget that a `gl-component` is **not** necessarily a `vue-component`

Though, I'll have a look about the possibility of the thing

**Comment by eddow** [comment]
Indeed it was easy.
The version 2.0.7 includes a `gl-component` `v-model` that is an object that will be included in the global state.

**Comment by tristanp2** [comment]
Thanks for getting back to me. I just realized that the link in my last comment was wrong. I did look at that part of the demo app for clues as to how I could accomplish my goal, but I was having strange cryptic errors from within Vue code and eventually I just needed to try a different approach. 

One thing I find pretty confusing is how exactly the Vue state relates to the golden layout state. In the example you gave from the demo app, what determines where a vue component will be shown in the layout? If you add some items to the d-stack in demo-stack.vue and then drag them to a different stack, the layout is properly persisted, even though the template shows a different structure to what is being rendered. I know you've mentioned in the readme that the Vue structure can differ from the gl structure, but I'm pretty confused about how the render works in this case.

**Comment by eddow** [comment]
Well, the "where" is in the state given to the layout.
Of course, both the Vue content and the gl-status "disposition" have to match. If you try to load a layout-status who specifies 2 stack items while loading only one in the Vue structure, there will be an exception.

For the technical part, the g-l object indeed has a link to its Vue correspondant and, when serializing, only remember its path in the Vue tree. (sth like "0.1.2.0")

**Comment by eddow** [comment]
**WARNING**: Don't jump on the `v-model` version, I'll try to see if I cannot do something nicer, allowing these states to be stored for every `gl-something` rather than just `gl-components`

**Comment by eddow** [comment]
So, it's a bit of a breaking change but I didn't consider it candidate for major version change :p
Instead of `v-model`, `:state.sync` is now used, and is also available for `<gl-row>`, `<gl-stack>`, &c.
