### ISSUE TITLE
How to catch errors

### ISSUE THREAD

**Issue by 2xAA** [emedware/vue-golden-layout#78]
If Golden Layout throws an error it seems very difficult to catch the error through Vue.

It would be great if we could use [Vue's `errorCaptured`](https://vuejs.org/v2/api/#errorCaptured) lifecycle hook for this.

An example use-case for this would be restoring layouts;

There is an unrecoverable error if Golden Layout's state cannot be loaded. I would like to mount `<GoldenLayout />` again after setting a flag to load the default layout when the error has been captured.

**Comment by eddow** [comment]
Well, the loading error is a particular case as it is managed by jQuery.

What you have to do here is to override `jQuery.readyException` who, in jQuery, is defined as this : 
```js
jQuery.readyException = function( error ) {
	window.setTimeout( function() {
		throw error;
	} );
};
``

**Comment by eddow** [comment]
I will indeed add it in the demo soon

**Comment by eddow** [comment]
https://github.com/emedware/vue-golden-layout/pull/86
The event `creation-error` has been added to the `golden-layout` object and raises on component creation. Mainly, when the config is missmatching the Vue structure.
