### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by bcopy** [emedware/vue-golden-layout#81]
Hello,

Can you please add a license to your package.json, to indicate the terms of usage for your NPM module ?
This is preventing automated deployment and license compliance analysis.

Golden Layout uses an MIT license for instance :
https://github.com/golden-layout/golden-layout/blob/master/package.json

Thanks,
Brice

**Comment by eddow** [comment]
There is already the `"license": "ISC"` line (30) - I don't understand the request

**Comment by bcopy** [comment]
sorry my bad, I'll ask the Webjars guys to add support for the ISC license

**Comment by eddow** [comment]
note: it's the MIT one in "easy english" version
