### ISSUE TITLE
destroy function of gl-component called twice

### ISSUE THREAD

**Issue by SangJuBaek** [emedware/vue-golden-layout#82]
Hello,

I confirmed that the 'destroy function' of 'gl-component' was called twice.

The same thing happens in Demo, and we saw that the exception process prevented the error from occurring.
Is there a way to resolve this part so that it can be called only once fundamentally?

**Comment by eddow** [comment]
Corrected and pushed - note that I only commented in the case of it now misses an event raising. Tell me if you need it published

**Comment by SangJuBaek** [comment]
I downloaded the demo again and ran it, and found the following error when I tried to destroy the gl-component:
![image](https://user-images.githubusercontent.com/6037505/88516948-0edfb580-d029-11ea-8299-51c9b8a43d3f.png)
I annotated the corresponding watch section in child.ts. No errors have occurred since then.
What problems will occur with the entire logic if this part is annotated? If there is no problem, can you publish after annotated?
