### ISSUE TITLE
How to get the width of a container

### ISSUE THREAD

**Issue by Johnly1986** [emedware/vue-golden-layout#85]
How to get the width of a container. such as the width of the container represented by the <gl-component> </gl-component> label.

**Comment by eddow** [comment]
If you add a reference to a component (ex. `demo-stack.js`:3)
```xml
		<gl-component title="compA" class="test-component" width="30" :state.sync="testState" ref="componentA">
```
then in the code, you will be able to reference it like this :
```js
this.$refs.componentA.container.width
```
